services:
  mongodb:
    container_name: monix-mongodb
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  server:
    container_name: monix-server
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
        reservations:
          memory: 256M
    build:
      context: ./server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6200:6200"
    volumes:
      - certs_data:/usr/src/app/certs
    depends_on:
      - mongodb

volumes:
  mongo_data: {}
  certs_data: {}
