export interface FishTypeInfo {
  id: string;
  name: string;
  icon: string;
  min_weight: number;
  max_weight: number;
  rarity_weight: number;
  base_price: number;
}

export const fishTypes: FishTypeInfo[] = [
  {
    id: 'cod',
    name: 'Cod',
    icon: '🐟',
    min_weight: 1,
    max_weight: 10,
    rarity_weight: 32,
    base_price: 100,
  },
  {
    id: 'salmon',
    name: 'Salmon',
    icon: '🐠',
    min_weight: 1,
    max_weight: 12,
    rarity_weight: 35,
    base_price: 120,
  },
  {
    id: 'clownfish',
    name: 'Clownfish',
    icon: '🐡',
    min_weight: 1,
    max_weight: 5,
    rarity_weight: 15,
    base_price: 200,
  },
  {
    id: 'shark',
    name: 'Shark',
    icon: '🦈',
    min_weight: 10,
    max_weight: 50,
    rarity_weight: 85,
    base_price: 500,
  },
  {
    id: 'stingray',
    name: 'Stingray',
    icon: '🐠',
    min_weight: 5,
    max_weight: 30,
    rarity_weight: 45,
    base_price: 300,
  },
  {
    id: 'whale',
    name: 'Whale',
    icon: '🐋',
    min_weight: 50,
    max_weight: 200,
    rarity_weight: 95,
    base_price: 1000,
  },
  {
    id: 'trout',
    name: 'Trout',
    icon: '🐟',
    min_weight: 1,
    max_weight: 10,
    rarity_weight: 30,
    base_price: 150,
  },
  {
    id: 'orca',
    name: 'Orca',
    icon: '🐳',
    min_weight: 30,
    max_weight: 100,
    rarity_weight: 90,
    base_price: 800,
  },
  {
    id: 'swordfish',
    name: 'Swordfish',
    icon: '🐟',
    min_weight: 15,
    max_weight: 60,
    rarity_weight: 70,
    base_price: 400,
  },
  {
    id: 'crocodile',
    name: 'Crocodile',
    icon: '🐊',
    min_weight: 20,
    max_weight: 80,
    rarity_weight: 75,
    base_price: 450,
  },
  {
    id: 'alligator',
    name: 'Alligator',
    icon: '🐊',
    min_weight: 20,
    max_weight: 80,
    rarity_weight: 75,
    base_price: 450,
  },
  {
    id: 'lobster',
    name: 'Lobster',
    icon: '🦞',
    min_weight: 5,
    max_weight: 20,
    rarity_weight: 40,
    base_price: 350,
  },
  {
    id: 'crab',
    name: 'Crab',
    icon: '🦀',
    min_weight: 3,
    max_weight: 15,
    rarity_weight: 25,
    base_price: 250,
  },
  {
    id: 'prawn',
    name: 'Prawn',
    icon: '🍤',
    min_weight: 1,
    max_weight: 8,
    rarity_weight: 20,
    base_price: 180,
  },
  {
    id: 'cuttlefish',
    name: 'Cuttlefish',
    icon: '🐙',
    min_weight: 4,
    max_weight: 18,
    rarity_weight: 50,
    base_price: 320,
  },
  {
    id: 'snapper',
    name: 'Snapper',
    icon: '🐟',
    min_weight: 2,
    max_weight: 12,
    rarity_weight: 38,
    base_price: 220,
  },
  {
    id: 'haddock',
    name: 'Haddock',
    icon: '🐟',
    min_weight: 2,
    max_weight: 11,
    rarity_weight: 28,
    base_price: 200,
  },
  {
    id: 'flathead',
    name: 'Flathead',
    icon: '🐟',
    min_weight: 1,
    max_weight: 9,
    rarity_weight: 22,
    base_price: 170,
  },
  {
    id: 'grouper',
    name: 'Grouper',
    icon: '🐠',
    min_weight: 6,
    max_weight: 25,
    rarity_weight: 42,
    base_price: 280,
  },
  {
    id: 'anglerfish',
    name: 'Anglerfish',
    icon: '🐡',
    min_weight: 3,
    max_weight: 14,
    rarity_weight: 18,
    base_price: 160,
  },
  {
    id: 'jellyfish',
    name: 'Jellyfish',
    icon: '🪼',
    min_weight: 1,
    max_weight: 7,
    rarity_weight: 12,
    base_price: 140,
  },
  {
    id: 'squid',
    name: 'Squid',
    icon: '🦑',
    min_weight: 4,
    max_weight: 16,
    rarity_weight: 48,
    base_price: 300,
  },
  {
    id: 'octopus',
    name: 'Octopus',
    icon: '🐙',
    min_weight: 5,
    max_weight: 20,
    rarity_weight: 55,
    base_price: 350,
  },
  {
    id: 'oyster',
    name: 'Oyster',
    icon: '🦪',
    min_weight: 1,
    max_weight: 5,
    rarity_weight: 14,
    base_price: 150,
  },
  {
    id: 'goldfish',
    name: 'Goldfish',
    icon: '🐠',
    min_weight: 1,
    max_weight: 4,
    rarity_weight: 12,
    base_price: 130,
  },
  {
    id: 'pufferfish',
    name: 'Pufferfish',
    icon: '🐡',
    min_weight: 2,
    max_weight: 9,
    rarity_weight: 33,
    base_price: 210,
  },
  {
    id: 'eel',
    name: 'Eel',
    icon: '🐍',
    min_weight: 3,
    max_weight: 14,
    rarity_weight: 18,
    base_price: 160,
  },
];
