export interface FishModifierInfo {
  id: string;
  name: string;
  icon?: string;
  event: string;
  multiplier: number;
  rarity_weight: number;
}

export const fishModifiers: FishModifierInfo[] = [
  {
    id: 'windstruck',
    name: 'Windstruck',
    icon: '💨',
    event: 'stormbreak',
    multiplier: 1.1,
    rarity_weight: 65,
  },
  {
    id: 'thunderstruck',
    name: 'Thunderstruck',
    icon: '⚡',
    event: 'stormbreak',
    multiplier: 1.18,
    rarity_weight: 25,
  },
  {
    id: 'electrified',
    name: 'Electrified',
    icon: '🔌',
    event: 'stormbreak',
    multiplier: 1.25,
    rarity_weight: 10,
  },
  {
    id: 'celestial',
    name: 'Celestial',
    icon: '🌌',
    event: 'stardom',
    multiplier: 1.3,
    rarity_weight: 80,
  },
  {
    id: 'starstruck',
    name: 'Starstruck',
    icon: '🌠',
    event: 'stardom',
    multiplier: 1.5,
    rarity_weight: 15,
  },
  {
    id: 'galactic',
    name: 'Galactic',
    icon: '🌌',
    event: 'stardom',
    multiplier: 1.7,
    rarity_weight: 5,
  },
  {
    id: 'radioactive',
    name: 'Radioactive',
    icon: '☢️',
    event: 'fallout',
    multiplier: 0.9,
    rarity_weight: 60,
  },
  {
    id: 'toxic',
    name: 'Toxic',
    icon: '☣️',
    event: 'fallout',
    multiplier: 0.85,
    rarity_weight: 25,
  },
  {
    id: 'hazardous',
    name: 'Hazardous',
    icon: '☠️',
    event: 'fallout',
    multiplier: 1.4,
    rarity_weight: 15,
  },
  {
    id: 'slimy',
    name: 'Slimy',
    icon: '🟢',
    event: 'slimeification',
    multiplier: 0.75,
    rarity_weight: 100,
  },
  {
    id: 'shiny',
    name: 'Shiny',
    icon: '✨',
    event: 'reflection',
    multiplier: 2.5,
    rarity_weight: 85,
  },
  {
    id: 'glassy',
    name: 'Glassy',
    icon: '🪞',
    event: 'reflection',
    multiplier: 3,
    rarity_weight: 14,
  },
  {
    id: 'iridescent',
    name: 'Iridescent',
    icon: '🪞',
    event: 'reflection',
    multiplier: 5,
    rarity_weight: 1,
  },
  {
    id: 'rainbow',
    name: 'Rainbow',
    icon: '🌈',
    event: 'rainbow',
    multiplier: 6,
    rarity_weight: 100,
  },
  {
    id: 'hopeful',
    name: 'Hopeful',
    icon: '🌈',
    event: 'newyear',
    multiplier: 1.15,
    rarity_weight: 100,
  },
  {
    id: 'melancholic',
    name: 'Melancholic',
    icon: '😢',
    event: 'sadness',
    multiplier: 0.9,
    rarity_weight: 60,
  },
  {
    id: 'weepy',
    name: 'Weepy',
    icon: '😭',
    event: 'sadness',
    multiplier: 0.85,
    rarity_weight: 30,
  },
  {
    id: 'distraught',
    name: 'Distraught',
    icon: '😭',
    event: 'sadness',
    multiplier: 0.8,
    rarity_weight: 10,
  },
  {
    id: 'joyful',
    name: 'Joyful',
    icon: '😄',
    event: 'happiness',
    multiplier: 1.1,
    rarity_weight: 60,
  },
  {
    id: 'peaceful',
    name: 'Peaceful',
    icon: '😊',
    event: 'happiness',
    multiplier: 1.15,
    rarity_weight: 30,
  },
  {
    id: 'elated',
    name: 'Elated',
    icon: '😆',
    event: 'happiness',
    multiplier: 1.25,
    rarity_weight: 10,
  },
  {
    id: 'spooky',
    name: 'Spooky',
    icon: '🎃',
    event: 'halloween',
    multiplier: 1.1,
    rarity_weight: 40,
  },
  {
    id: 'ghostly',
    name: 'Ghostly',
    icon: '👻',
    event: 'halloween',
    multiplier: 1.3,
    rarity_weight: 25,
  },
  {
    id: 'petrified',
    name: 'Petrified',
    icon: '🪨',
    event: 'halloween',
    multiplier: 1.4,
    rarity_weight: 10,
  },
  {
    id: 'mortified',
    name: 'Mortified',
    icon: '💀',
    event: 'halloween',
    multiplier: 1.18,
    rarity_weight: 15,
  },
  {
    id: 'freaky',
    name: 'Freaky',
    icon: '🎃',
    event: 'halloween',
    multiplier: 1.12,
    rarity_weight: 10,
  },
  {
    id: 'dreaming',
    name: 'Dreaming',
    icon: '💤',
    event: 'souls',
    multiplier: 1.12,
    rarity_weight: 65,
  },
  {
    id: 'mysterious',
    name: 'Mysterious',
    icon: '👻',
    event: 'souls',
    multiplier: 1.25,
    rarity_weight: 25,
  },
  {
    id: 'abyssal',
    name: 'Abyssal',
    icon: '🌊',
    event: 'souls',
    multiplier: 1.6,
    rarity_weight: 10,
  },
  {
    id: 'jolly',
    name: 'Jolly',
    icon: '🎄',
    event: 'christmas',
    multiplier: 1.2,
    rarity_weight: 100,
  },
  {
    id: 'cursed',
    name: 'Cursed',
    icon: '🪦',
    event: 'wizards',
    multiplier: 1.22,
    rarity_weight: 60,
  },
  {
    id: 'blessed',
    name: 'Blessed',
    icon: '✨',
    event: 'wizards',
    multiplier: 0.7,
    rarity_weight: 25,
  },
  {
    id: 'spellbound',
    name: 'Spellbound',
    icon: '🪄',
    event: 'wizards',
    multiplier: 1.35,
    rarity_weight: 15,
  },
  {
    id: 'love-struck',
    name: 'Love-Struck',
    icon: '💘',
    event: 'valentines',
    multiplier: 1.2,
    rarity_weight: 75,
  },
  {
    id: 'heartbroken',
    name: 'Heartbroken',
    icon: '💔',
    event: 'valentines',
    multiplier: 0.9,
    rarity_weight: 25,
  },
];
