// This file is automatically overwritten by a script.
// It contains the current version of the application.
// Please do not edit this file directly.

// This is what the script will write into this file:
export const COMMIT: string = '$COMMIT_HASH';
export const COMMIT_NUMBER_THIS_MONTH: string = '$COMMIT_NUMBER_THIS_MONTH';
export const BUILD_TIMESTAMP: string = '$TIMESTAMP';
