import type { Cosmetic } from './cosmetic';

export const cosmetics: Cosmetic[] = [
  // Tags
  {
    id: 'og-tag',
    name: 'OG Tag',
    type: 'tag',
    tagIcon: '🔥',
    tagName: 'OG',
    tagColour: 'red',
    rarity: 'godlike',
    buyable: false,
  },
  {
    id: 'mwga-tag',
    name: 'MWGA Tag',
    type: 'tag',
    tagIcon: '💧',
    tagName: 'MWGA',
    tagColour: 'blue',
    rarity: 'godlike',
    buyable: false,
  },
  {
    id: 'cool-tag',
    name: 'Cool Tag',
    type: 'tag',
    tagIcon: '😎',
    tagName: 'Cool',
    tagColour: 'purple',
    rarity: 'uncommon',
    buyable: true,
    price: 100,
  },
  {
    id: 'aurora-tag',
    name: 'Aurora Tag',
    type: 'tag',
    tagIcon: '✨',
    tagName: 'Aurora',
    tagColour: 'primary',
    rarity: 'rare',
    buyable: true,
    price: 180,
  },
  {
    id: 'forge-tag',
    name: 'Forge Tag',
    type: 'tag',
    tagIcon: '🛠️',
    tagName: 'Forge',
    tagColour: 'red',
    rarity: 'rare',
    buyable: true,
    price: 200,
  },
  {
    id: 'drift-tag',
    name: 'Drift Tag',
    type: 'tag',
    tagIcon: '🌊',
    tagName: 'Drift',
    tagColour: 'blue',
    rarity: 'uncommon',
    buyable: true,
    price: 140,
  },
  {
    id: 'arcade-tag',
    name: 'Arcade Tag',
    type: 'tag',
    tagIcon: '🕹️',
    tagName: 'Arcade',
    tagColour: 'purple',
    rarity: 'epic',
    buyable: true,
    price: 320,
  },
  {
    id: 'blaze-tag',
    name: 'Blaze Tag',
    type: 'tag',
    tagIcon: '🔥',
    tagName: 'Blaze',
    tagColour: 'red',
    rarity: 'epic',
    buyable: true,
    price: 350,
  },

  // Nameplates
  {
    id: 'gold-nameplate',
    name: 'Gold Nameplate',
    type: 'nameplate',
    nameplateStyle: 'gold',
    rarity: 'epic',
    buyable: true,
    price: 500,
  },
  {
    id: 'sakura-nameplate',
    name: 'Sakura Nameplate',
    type: 'nameplate',
    nameplateStyle: 'sakura',
    rarity: 'epic',
    buyable: true,
    price: 500,
  },
  {
    id: 'ember-nameplate',
    name: 'Ember Nameplate',
    type: 'nameplate',
    nameplateStyle: 'ember',
    rarity: 'rare',
    buyable: true,
    price: 350,
  },
  {
    id: 'glacier-nameplate',
    name: 'Glacier Nameplate',
    type: 'nameplate',
    nameplateStyle: 'glacier',
    rarity: 'epic',
    buyable: true,
    price: 520,
  },
  {
    id: 'verdant-nameplate',
    name: 'Verdant Nameplate',
    type: 'nameplate',
    nameplateStyle: 'verdant',
    rarity: 'rare',
    buyable: true,
    price: 380,
  },
  {
    id: 'nebula-nameplate',
    name: 'Nebula Nameplate',
    type: 'nameplate',
    nameplateStyle: 'nebula',
    rarity: 'legendary',
    buyable: true,
    price: 750,
  },
  {
    id: 'citrine-nameplate',
    name: 'Citrine Nameplate',
    type: 'nameplate',
    nameplateStyle: 'citrine',
    rarity: 'epic',
    buyable: true,
    price: 540,
  },

  // Frames
  {
    id: 'dark-frame',
    name: 'Dark Frame',
    type: 'frame',
    frameStyle: 'dark',
    rarity: 'rare',
    buyable: true,
    price: 320,
  },
];
